# Generated by Django 6.0.5 on 2026-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=200)),
                ('poster', models.URLField(blank=True, default='N/A')),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('compra', 'Solo Compra'), ('alquiler', 'Solo Alquiler'), ('compra_alquiler', 'Compra y Alquiler')], default='compra_alquiler', max_length=20)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['titulo'],
            },
        ),
    ]
